TABLE_LEAGUES, TABLE_FIXTURES, TABLE_ODDS, TABLE_RESULTS, TABLE_OPENING, TABLE_CLOSING = 'leagues', 'fixtures', 'odds', 'results', 'opening', 'closing'

SPORTS = dict()
SPORTS.update({'Soccer': 29})
SPORTS.update({'Tennis': 33})
SPORTS.update({'Basketball': 4})
SPORTS.update({'Hockey': 19})
SPORTS.update({'Volleyball': 34})
SPORTS.update({'Handball': 18})
SPORTS.update({'Football': 15})
SPORTS.update({'Mixed Martial Arts': 22})
SPORTS.update({'Baseball': 3})

PERIODS = dict()
PERIODS.update({(29, 0): 'Match'})
PERIODS.update({(29, 1): '1st Half'})
PERIODS.update({(4, 0): 'Game'})
PERIODS.update({(4, 1): '1st Half'})
PERIODS.update({(4, 3): '1st Quarter'})
PERIODS.update({(33, 0): 'Match'})
PERIODS.update({(33, 1): '1st Set'})
PERIODS.update({(3, 0): 'Game'})
PERIODS.update({(3, 1): '1st Half'})
PERIODS.update({(3, 3): '1st Inning'})
PERIODS.update({(15, 0): 'Game'})
PERIODS.update({(15, 1): '1st Half'})
PERIODS.update({(15, 3): '1st Quarter'})
PERIODS.update({(19, 0): 'OT Included'})
PERIODS.update({(19, 1): '1st Period'})
PERIODS.update({(19, 6): 'Regulation Time'})
PERIODS.update({(18, 0): 'Match'})
PERIODS.update({(18, 1): '1st Half'})
PERIODS.update({(34, 0): 'Match'})
PERIODS.update({(34, 1): '1st Set'})
PERIODS.update({(22, 0): 'Fight'})
PERIODS.update({(22, 1): 'Round 1'})

